#######################################################################
#            moresand hello-world App - Docker-compose v0.1          #
#######################################################################


version: '3.7'
services:

     nginx:
        image: moresand-nginx:1.1
        container_name: moresand-hello-world-lb
        ports:
          - "80:80"
        volumes: 
          - ./nginx-conf/:/etc/nginx/conf.d/ 


     tomcat110:
        image: moresand-hello:1.1
        container_name: moresand-hello-world-tomcat

        ports:
          - '8080:8080'


